---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worker-staging
  namespace: instavote
spec:
  dependsOn:
  - name: redis-staging
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1m0s
  path: ./deploy/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 2m0s
